### ISSUE TITLE
File gets appended instead of overwritten?

### ISSUE THREAD

**Issue by stdedos** [awelzel/flake8-gl-codeclimate#13]
Hello there! I am using a pre-commit hook, like so:

```yml
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-type-checking
          - flake8-gl-codeclimate
        args: [
          --format, gl-codeclimate,
          --output-file, flake8-GitlabCodeClimateReporter.json
        ]
```

and, from time to time, I see that `flake8-GitlabCodeClimateReporter.json` looks like:
```json
[]
[]
[]
[]
[]

```

instead of, at all times:
```json
[]
```
which is a little weird for me.

Is it possible that, instead of opening the file to write, you open it to append? (... and that's something that falls within this repo?)
